package archtest

// ErrorAllowlist maps file paths (relative to module root) to the maximum
// number of allowed fmt.Errorf calls that do NOT use %w for error wrapping.
//
// This is a ratchet mechanism: the actual violation count must be ≤ the
// allowed count. When a file's violations are reduced, lower the number here
// to prevent regressions. New files must be added with count=0 (or fixed
// immediately).
//
// To regenerate counts after intentional clean-up:
//   go run scripts/update-errorf-ratchet.go
// Or manually decrease a value when you fix violations in a file.
type ErrorAllowlist map[string]int

// DefaultAllowlist is the ratchet baseline captured from the current codebase.
// Generated from: T-ARCH-000-0 reconnaissance (396 violations across 86 files).
var DefaultAllowlist = ErrorAllowlist{
	"cmd/c4/auth.go":                               6,
	"cmd/c4/research_checkpoint.go":                2,
	"cmd/c4/research_debate.go":                    2,
	"cmd/c4/research_level3.go":                    1,
	"cmd/c4/research_spec.go":                      3,
	"cmd/c4/hypothesis.go":                         3,
	"cmd/c4/serve_hypothesis_suggester.go":         1,
	"cmd/c4/serve_knowledge_suggestpoller.go":      5,
	"cmd/c4/cloud.go":                              1,
	"cmd/c4/upgrade.go":                            1,
	"cmd/c4/worker.go":                             3,
	"cmd/c4/tool.go":                               1,
	"cmd/c4/daemon.go":                             1,
	"cmd/c4/drive.go":                              5,
	"cmd/c4/embed_c5_stub.go":                      1,
	"cmd/c4/eventbus.go":                           6,
	"cmd/c4/fallback.go":                           2,
	"cmd/c4/hub.go":                                8,
	"cmd/c4/hub_worker.go":                         7,
	"cmd/c4/init.go":                               7,
	"cmd/c4/mail.go":                               3,
	"cmd/c4/mcp_supabase.go":                       2,
	"cmd/c4/root.go":                               1,
	"cmd/c4/run.go":                                2,
	"cmd/c4/secret.go":                             1,
	"cmd/c4/serve.go":                              1,
	"cmd/c4/stop.go":                               1,
	"internal/bridge/sidecar.go":                   8,
	"internal/channelpush/pusher.go":                3,
	"internal/webcontent/fetch.go":              8,
	"internal/cdp/cdp.go":                          5,
	"internal/cdp/webmcp.go":                       9,
	"internal/cloud/auth.go":                       8,
	"internal/cloud/device_flow.go":                6,
	"internal/cloud/knowledge.go":                  5,
	"internal/cloud/store.go":                      13,
	"internal/daemon/gpu.go":                       2,
	"internal/daemon/store.go":                     4,
	"internal/drive/client.go":                     11,
	"internal/drive/dataset.go":                    11,
	"internal/eventbus/dispatcher.go":              19,
	"internal/eventbus/store.go":                   6,
	"internal/gate/connectors.go":                  2,
	"internal/gate/scheduler.go":                   2,
	"internal/gate/webhook.go":                     2,
	"internal/goast/parser.go":                     2,
	"internal/guard/middleware.go":                 3,
	"internal/hub/artifact.go":                     2,
	"internal/hub/client.go":                       6,
	"internal/hub/edge.go":                         3,
	"internal/hub/worker.go":                       3,
	"internal/knowledge/ingest.go":                 2,
	"internal/knowledge/search.go":                 1,
	"internal/knowledge/sync.go":                   4,
	"internal/knowledge/vector.go":                 3,
	"internal/llm/anthropic.go":                    2,
	"internal/llm/gateway.go":                      5,
	"internal/llm/gemini.go":                       2,
	"internal/llm/ollama.go":                       4,
	"internal/llm/openai.go":                       4,
	"internal/mailbox/mailbox.go":                  2,
	"internal/mcp/handlers/c1handler/c1.go":         12,
	"internal/mcp/handlers/c1handler/c1_keeper.go": 5,
	"internal/mcp/handlers/cdphandler/cdp.go":      22,
	"internal/mcp/handlers/cfghandler/cfghandler.go": 1,
	"internal/mcp/handlers/drivehandler/drive.go":  5,
	"internal/mcp/handlers/eventbushandler/eventbus.go": 8,
	"internal/mcp/handlers/fileops/fileops.go":      3,
	"internal/mcp/handlers/files_helpers.go":       2,
	"internal/mcp/handlers/git_helpers.go":         1,
	"internal/mcp/handlers/gitops/gitops.go":       1,
	"internal/mcp/handlers/handlers_gate.go":       6,
	"internal/mcp/handlers/handlers_guard.go":      6,
	"internal/mcp/handlers/handlers_observe.go":    3,
	"internal/mcp/handlers/hubhandler/hub_dag.go":          6,
	"internal/mcp/handlers/hubhandler/hub_edge.go":         6,
	"internal/mcp/handlers/hubhandler/hub_infra.go":        2,
	"internal/mcp/handlers/hubhandler/hub_jobs.go":         7,
	"internal/mcp/handlers/hubhandler/hub_jobs_metrics.go": 4,
	"internal/mcp/handlers/knowledgehandler/knowledge_record.go": 1,
	"internal/mcp/handlers/notifyhandler/notifyhandler.go":       5,
	"internal/notify/notify.go":                                  2,
	"internal/mcp/handlers/lighthouse.go":          17,
	"internal/mcp/handlers/llmhandler/llm.go":      1,
	"internal/mcp/handlers/artifacthandler/artifacthandler.go": 2,
	"internal/mcp/handlers/mailhandler/mailhandler.go":         8,
	"internal/mcp/handlers/persona.go":             4,
	"internal/mcp/handlers/phase_lock.go":          4,
	"internal/mcp/handlers/proxy.go":               6,
	"internal/mcp/handlers/secrethandler/secrethandler.go": 10,
	"internal/mcp/handlers/soul.go":                7,
	"internal/mcp/handlers/sqlite_store.go":        12,
	"internal/mcp/handlers/store_review.go":        3,
	"internal/mcp/handlers/tasks.go":               20,
	"internal/mcp/handlers/tracking.go":            8,
	"cmd/c4/serve_loop_orchestrator.go":            6,
	"cmd/c4/serve_loop_orchestrator_jobdone.go":    2,
	"internal/mcp/handlers/worker_standby.go":      8,
	"internal/mcp/mcp.go":                          1,
	"internal/secrets/store.go":                    3,
	"internal/secrets/supabase_sync.go":            4, // HTTP status error messages (no underlying error to wrap)
	"internal/serve/agent.go":                      4,
	"internal/serve/gpu_component.go":              1,
	"internal/serve/hub_component.go":              2,
	"internal/serve/hubpoller_component.go":        2,
	"internal/serve/realtime.go":                   3,
	"internal/serve/ssesubscriber.go":              2,
	"internal/state/machine.go":                    2,
	"internal/skilleval/generator.go":              1,
	"internal/skilleval/runner.go":                 2,
	"internal/task/models.go":                      6,
	// Files added after T-ARCH-000-0 baseline — ratcheted at current counts.
	"internal/chat/client.go":                                    4,
	"internal/chat/router.go":                                    2,
	"internal/mcp/handlers/c2_native.go":                         2,
	"internal/serve/hypothesissuggester/hypothesissuggester.go":  1,
	"internal/serve/orchestrator/jobdone.go":                     4,
	"internal/serve/orchestrator/orchestrator.go":                6,
	"internal/serve/suggestpoller/suggestpoller.go":              5,
	"cmd/c4/chat.go":                                             7,
	"cmd/c4/hub_transfer.go":                                     5,
	"cmd/c4/secret_windows.go":                                   1,
}
