// Code generated by hand (stub). DO NOT EDIT.
// This file provides stub gRPC service interfaces that match protoc-gen-go-grpc output.
// Run `make proto-gen` to replace with actual generated code.

package pb

import (
	"context"

	"google.golang.org/grpc"
	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/status"
)

// BridgeServiceClient is the client API for BridgeService.
type BridgeServiceClient interface {
	GetState(ctx context.Context, in *GetStateRequest, opts ...grpc.CallOption) (*GetStateResponse, error)
	TransitionState(ctx context.Context, in *TransitionStateRequest, opts ...grpc.CallOption) (*TransitionStateResponse, error)
	GetTask(ctx context.Context, in *GetTaskRequest, opts ...grpc.CallOption) (*GetTaskResponse, error)
	SubmitTask(ctx context.Context, in *SubmitTaskRequest, opts ...grpc.CallOption) (*SubmitTaskResponse, error)
	RunValidation(ctx context.Context, in *RunValidationRequest, opts ...grpc.CallOption) (*RunValidationResponse, error)

	FindSymbol(ctx context.Context, in *FindSymbolRequest, opts ...grpc.CallOption) (*FindSymbolResponse, error)
	GetSymbolsOverview(ctx context.Context, in *GetSymbolsOverviewRequest, opts ...grpc.CallOption) (*GetSymbolsOverviewResponse, error)
	ReplaceSymbolBody(ctx context.Context, in *ReplaceSymbolBodyRequest, opts ...grpc.CallOption) (*ReplaceSymbolBodyResponse, error)
	InsertBeforeSymbol(ctx context.Context, in *InsertSymbolRequest, opts ...grpc.CallOption) (*InsertSymbolResponse, error)
	InsertAfterSymbol(ctx context.Context, in *InsertSymbolRequest, opts ...grpc.CallOption) (*InsertSymbolResponse, error)
	RenameSymbol(ctx context.Context, in *RenameSymbolRequest, opts ...grpc.CallOption) (*RenameSymbolResponse, error)

	KnowledgeSearch(ctx context.Context, in *KnowledgeSearchRequest, opts ...grpc.CallOption) (*KnowledgeSearchResponse, error)
	KnowledgeRecord(ctx context.Context, in *KnowledgeRecordRequest, opts ...grpc.CallOption) (*KnowledgeRecordResponse, error)
	KnowledgeGet(ctx context.Context, in *KnowledgeGetRequest, opts ...grpc.CallOption) (*KnowledgeGetResponse, error)

	GPUStatus(ctx context.Context, in *GPUStatusRequest, opts ...grpc.CallOption) (*GPUStatusResponse, error)
	JobSubmit(ctx context.Context, in *JobSubmitRequest, opts ...grpc.CallOption) (*JobSubmitResponse, error)
}

type bridgeServiceClient struct {
	cc grpc.ClientConnInterface
}

// NewBridgeServiceClient returns a new BridgeServiceClient.
func NewBridgeServiceClient(cc grpc.ClientConnInterface) BridgeServiceClient {
	return &bridgeServiceClient{cc}
}

const bridgeServiceName = "/c4.bridge.BridgeService/"

func (c *bridgeServiceClient) GetState(ctx context.Context, in *GetStateRequest, opts ...grpc.CallOption) (*GetStateResponse, error) {
	out := new(GetStateResponse)
	err := c.cc.Invoke(ctx, bridgeServiceName+"GetState", in, out, opts...)
	return out, err
}

func (c *bridgeServiceClient) TransitionState(ctx context.Context, in *TransitionStateRequest, opts ...grpc.CallOption) (*TransitionStateResponse, error) {
	out := new(TransitionStateResponse)
	err := c.cc.Invoke(ctx, bridgeServiceName+"TransitionState", in, out, opts...)
	return out, err
}

func (c *bridgeServiceClient) GetTask(ctx context.Context, in *GetTaskRequest, opts ...grpc.CallOption) (*GetTaskResponse, error) {
	out := new(GetTaskResponse)
	err := c.cc.Invoke(ctx, bridgeServiceName+"GetTask", in, out, opts...)
	return out, err
}

func (c *bridgeServiceClient) SubmitTask(ctx context.Context, in *SubmitTaskRequest, opts ...grpc.CallOption) (*SubmitTaskResponse, error) {
	out := new(SubmitTaskResponse)
	err := c.cc.Invoke(ctx, bridgeServiceName+"SubmitTask", in, out, opts...)
	return out, err
}

func (c *bridgeServiceClient) RunValidation(ctx context.Context, in *RunValidationRequest, opts ...grpc.CallOption) (*RunValidationResponse, error) {
	out := new(RunValidationResponse)
	err := c.cc.Invoke(ctx, bridgeServiceName+"RunValidation", in, out, opts...)
	return out, err
}

func (c *bridgeServiceClient) FindSymbol(ctx context.Context, in *FindSymbolRequest, opts ...grpc.CallOption) (*FindSymbolResponse, error) {
	out := new(FindSymbolResponse)
	err := c.cc.Invoke(ctx, bridgeServiceName+"FindSymbol", in, out, opts...)
	return out, err
}

func (c *bridgeServiceClient) GetSymbolsOverview(ctx context.Context, in *GetSymbolsOverviewRequest, opts ...grpc.CallOption) (*GetSymbolsOverviewResponse, error) {
	out := new(GetSymbolsOverviewResponse)
	err := c.cc.Invoke(ctx, bridgeServiceName+"GetSymbolsOverview", in, out, opts...)
	return out, err
}

func (c *bridgeServiceClient) ReplaceSymbolBody(ctx context.Context, in *ReplaceSymbolBodyRequest, opts ...grpc.CallOption) (*ReplaceSymbolBodyResponse, error) {
	out := new(ReplaceSymbolBodyResponse)
	err := c.cc.Invoke(ctx, bridgeServiceName+"ReplaceSymbolBody", in, out, opts...)
	return out, err
}

func (c *bridgeServiceClient) InsertBeforeSymbol(ctx context.Context, in *InsertSymbolRequest, opts ...grpc.CallOption) (*InsertSymbolResponse, error) {
	out := new(InsertSymbolResponse)
	err := c.cc.Invoke(ctx, bridgeServiceName+"InsertBeforeSymbol", in, out, opts...)
	return out, err
}

func (c *bridgeServiceClient) InsertAfterSymbol(ctx context.Context, in *InsertSymbolRequest, opts ...grpc.CallOption) (*InsertSymbolResponse, error) {
	out := new(InsertSymbolResponse)
	err := c.cc.Invoke(ctx, bridgeServiceName+"InsertAfterSymbol", in, out, opts...)
	return out, err
}

func (c *bridgeServiceClient) RenameSymbol(ctx context.Context, in *RenameSymbolRequest, opts ...grpc.CallOption) (*RenameSymbolResponse, error) {
	out := new(RenameSymbolResponse)
	err := c.cc.Invoke(ctx, bridgeServiceName+"RenameSymbol", in, out, opts...)
	return out, err
}

func (c *bridgeServiceClient) KnowledgeSearch(ctx context.Context, in *KnowledgeSearchRequest, opts ...grpc.CallOption) (*KnowledgeSearchResponse, error) {
	out := new(KnowledgeSearchResponse)
	err := c.cc.Invoke(ctx, bridgeServiceName+"KnowledgeSearch", in, out, opts...)
	return out, err
}

func (c *bridgeServiceClient) KnowledgeRecord(ctx context.Context, in *KnowledgeRecordRequest, opts ...grpc.CallOption) (*KnowledgeRecordResponse, error) {
	out := new(KnowledgeRecordResponse)
	err := c.cc.Invoke(ctx, bridgeServiceName+"KnowledgeRecord", in, out, opts...)
	return out, err
}

func (c *bridgeServiceClient) KnowledgeGet(ctx context.Context, in *KnowledgeGetRequest, opts ...grpc.CallOption) (*KnowledgeGetResponse, error) {
	out := new(KnowledgeGetResponse)
	err := c.cc.Invoke(ctx, bridgeServiceName+"KnowledgeGet", in, out, opts...)
	return out, err
}

func (c *bridgeServiceClient) GPUStatus(ctx context.Context, in *GPUStatusRequest, opts ...grpc.CallOption) (*GPUStatusResponse, error) {
	out := new(GPUStatusResponse)
	err := c.cc.Invoke(ctx, bridgeServiceName+"GPUStatus", in, out, opts...)
	return out, err
}

func (c *bridgeServiceClient) JobSubmit(ctx context.Context, in *JobSubmitRequest, opts ...grpc.CallOption) (*JobSubmitResponse, error) {
	out := new(JobSubmitResponse)
	err := c.cc.Invoke(ctx, bridgeServiceName+"JobSubmit", in, out, opts...)
	return out, err
}

// BridgeServiceServer is the server API for BridgeService.
type BridgeServiceServer interface {
	GetState(context.Context, *GetStateRequest) (*GetStateResponse, error)
	TransitionState(context.Context, *TransitionStateRequest) (*TransitionStateResponse, error)
	GetTask(context.Context, *GetTaskRequest) (*GetTaskResponse, error)
	SubmitTask(context.Context, *SubmitTaskRequest) (*SubmitTaskResponse, error)
	RunValidation(context.Context, *RunValidationRequest) (*RunValidationResponse, error)

	FindSymbol(context.Context, *FindSymbolRequest) (*FindSymbolResponse, error)
	GetSymbolsOverview(context.Context, *GetSymbolsOverviewRequest) (*GetSymbolsOverviewResponse, error)
	ReplaceSymbolBody(context.Context, *ReplaceSymbolBodyRequest) (*ReplaceSymbolBodyResponse, error)
	InsertBeforeSymbol(context.Context, *InsertSymbolRequest) (*InsertSymbolResponse, error)
	InsertAfterSymbol(context.Context, *InsertSymbolRequest) (*InsertSymbolResponse, error)
	RenameSymbol(context.Context, *RenameSymbolRequest) (*RenameSymbolResponse, error)

	KnowledgeSearch(context.Context, *KnowledgeSearchRequest) (*KnowledgeSearchResponse, error)
	KnowledgeRecord(context.Context, *KnowledgeRecordRequest) (*KnowledgeRecordResponse, error)
	KnowledgeGet(context.Context, *KnowledgeGetRequest) (*KnowledgeGetResponse, error)

	GPUStatus(context.Context, *GPUStatusRequest) (*GPUStatusResponse, error)
	JobSubmit(context.Context, *JobSubmitRequest) (*JobSubmitResponse, error)

	mustEmbedUnimplementedBridgeServiceServer()
}

// UnimplementedBridgeServiceServer should be embedded to have forward compatible implementations.
type UnimplementedBridgeServiceServer struct{}

func (UnimplementedBridgeServiceServer) GetState(context.Context, *GetStateRequest) (*GetStateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetState not implemented")
}
func (UnimplementedBridgeServiceServer) TransitionState(context.Context, *TransitionStateRequest) (*TransitionStateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TransitionState not implemented")
}
func (UnimplementedBridgeServiceServer) GetTask(context.Context, *GetTaskRequest) (*GetTaskResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTask not implemented")
}
func (UnimplementedBridgeServiceServer) SubmitTask(context.Context, *SubmitTaskRequest) (*SubmitTaskResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SubmitTask not implemented")
}
func (UnimplementedBridgeServiceServer) RunValidation(context.Context, *RunValidationRequest) (*RunValidationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RunValidation not implemented")
}
func (UnimplementedBridgeServiceServer) FindSymbol(context.Context, *FindSymbolRequest) (*FindSymbolResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindSymbol not implemented")
}
func (UnimplementedBridgeServiceServer) GetSymbolsOverview(context.Context, *GetSymbolsOverviewRequest) (*GetSymbolsOverviewResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSymbolsOverview not implemented")
}
func (UnimplementedBridgeServiceServer) ReplaceSymbolBody(context.Context, *ReplaceSymbolBodyRequest) (*ReplaceSymbolBodyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReplaceSymbolBody not implemented")
}
func (UnimplementedBridgeServiceServer) InsertBeforeSymbol(context.Context, *InsertSymbolRequest) (*InsertSymbolResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InsertBeforeSymbol not implemented")
}
func (UnimplementedBridgeServiceServer) InsertAfterSymbol(context.Context, *InsertSymbolRequest) (*InsertSymbolResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InsertAfterSymbol not implemented")
}
func (UnimplementedBridgeServiceServer) RenameSymbol(context.Context, *RenameSymbolRequest) (*RenameSymbolResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RenameSymbol not implemented")
}
func (UnimplementedBridgeServiceServer) KnowledgeSearch(context.Context, *KnowledgeSearchRequest) (*KnowledgeSearchResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method KnowledgeSearch not implemented")
}
func (UnimplementedBridgeServiceServer) KnowledgeRecord(context.Context, *KnowledgeRecordRequest) (*KnowledgeRecordResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method KnowledgeRecord not implemented")
}
func (UnimplementedBridgeServiceServer) KnowledgeGet(context.Context, *KnowledgeGetRequest) (*KnowledgeGetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method KnowledgeGet not implemented")
}
func (UnimplementedBridgeServiceServer) GPUStatus(context.Context, *GPUStatusRequest) (*GPUStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GPUStatus not implemented")
}
func (UnimplementedBridgeServiceServer) JobSubmit(context.Context, *JobSubmitRequest) (*JobSubmitResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method JobSubmit not implemented")
}
func (UnimplementedBridgeServiceServer) mustEmbedUnimplementedBridgeServiceServer() {}

// UnsafeBridgeServiceServer may be embedded to opt out of forward compatibility for this service.
type UnsafeBridgeServiceServer interface {
	mustEmbedUnimplementedBridgeServiceServer()
}

// RegisterBridgeServiceServer registers the BridgeServiceServer with the gRPC server.
func RegisterBridgeServiceServer(s grpc.ServiceRegistrar, srv BridgeServiceServer) {
	sd := &grpc.ServiceDesc{
		ServiceName: "c4.bridge.BridgeService",
		HandlerType: (*BridgeServiceServer)(nil),
		Methods: []grpc.MethodDesc{
			{MethodName: "GetState", Handler: _BridgeService_GetState_Handler},
			{MethodName: "TransitionState", Handler: _BridgeService_TransitionState_Handler},
			{MethodName: "GetTask", Handler: _BridgeService_GetTask_Handler},
			{MethodName: "SubmitTask", Handler: _BridgeService_SubmitTask_Handler},
			{MethodName: "RunValidation", Handler: _BridgeService_RunValidation_Handler},
			{MethodName: "FindSymbol", Handler: _BridgeService_FindSymbol_Handler},
			{MethodName: "GetSymbolsOverview", Handler: _BridgeService_GetSymbolsOverview_Handler},
			{MethodName: "ReplaceSymbolBody", Handler: _BridgeService_ReplaceSymbolBody_Handler},
			{MethodName: "InsertBeforeSymbol", Handler: _BridgeService_InsertBeforeSymbol_Handler},
			{MethodName: "InsertAfterSymbol", Handler: _BridgeService_InsertAfterSymbol_Handler},
			{MethodName: "RenameSymbol", Handler: _BridgeService_RenameSymbol_Handler},
			{MethodName: "KnowledgeSearch", Handler: _BridgeService_KnowledgeSearch_Handler},
			{MethodName: "KnowledgeRecord", Handler: _BridgeService_KnowledgeRecord_Handler},
			{MethodName: "KnowledgeGet", Handler: _BridgeService_KnowledgeGet_Handler},
			{MethodName: "GPUStatus", Handler: _BridgeService_GPUStatus_Handler},
			{MethodName: "JobSubmit", Handler: _BridgeService_JobSubmit_Handler},
		},
		Streams:  []grpc.StreamDesc{},
		Metadata: "proto/c4_bridge.proto",
	}
	s.RegisterService(sd, srv)
}

// --- Handler functions ---

func _BridgeService_GetState_Handler(srv any, ctx context.Context, dec func(any) error, interceptor grpc.UnaryServerInterceptor) (any, error) {
	in := new(GetStateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BridgeServiceServer).GetState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{Server: srv, FullMethod: bridgeServiceName + "GetState"}
	return interceptor(ctx, in, info, func(ctx context.Context, req any) (any, error) { return srv.(BridgeServiceServer).GetState(ctx, req.(*GetStateRequest)) })
}

func _BridgeService_TransitionState_Handler(srv any, ctx context.Context, dec func(any) error, interceptor grpc.UnaryServerInterceptor) (any, error) {
	in := new(TransitionStateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BridgeServiceServer).TransitionState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{Server: srv, FullMethod: bridgeServiceName + "TransitionState"}
	return interceptor(ctx, in, info, func(ctx context.Context, req any) (any, error) {
		return srv.(BridgeServiceServer).TransitionState(ctx, req.(*TransitionStateRequest))
	})
}

func _BridgeService_GetTask_Handler(srv any, ctx context.Context, dec func(any) error, interceptor grpc.UnaryServerInterceptor) (any, error) {
	in := new(GetTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BridgeServiceServer).GetTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{Server: srv, FullMethod: bridgeServiceName + "GetTask"}
	return interceptor(ctx, in, info, func(ctx context.Context, req any) (any, error) { return srv.(BridgeServiceServer).GetTask(ctx, req.(*GetTaskRequest)) })
}

func _BridgeService_SubmitTask_Handler(srv any, ctx context.Context, dec func(any) error, interceptor grpc.UnaryServerInterceptor) (any, error) {
	in := new(SubmitTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BridgeServiceServer).SubmitTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{Server: srv, FullMethod: bridgeServiceName + "SubmitTask"}
	return interceptor(ctx, in, info, func(ctx context.Context, req any) (any, error) { return srv.(BridgeServiceServer).SubmitTask(ctx, req.(*SubmitTaskRequest)) })
}

func _BridgeService_RunValidation_Handler(srv any, ctx context.Context, dec func(any) error, interceptor grpc.UnaryServerInterceptor) (any, error) {
	in := new(RunValidationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BridgeServiceServer).RunValidation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{Server: srv, FullMethod: bridgeServiceName + "RunValidation"}
	return interceptor(ctx, in, info, func(ctx context.Context, req any) (any, error) {
		return srv.(BridgeServiceServer).RunValidation(ctx, req.(*RunValidationRequest))
	})
}

func _BridgeService_FindSymbol_Handler(srv any, ctx context.Context, dec func(any) error, interceptor grpc.UnaryServerInterceptor) (any, error) {
	in := new(FindSymbolRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BridgeServiceServer).FindSymbol(ctx, in)
	}
	info := &grpc.UnaryServerInfo{Server: srv, FullMethod: bridgeServiceName + "FindSymbol"}
	return interceptor(ctx, in, info, func(ctx context.Context, req any) (any, error) { return srv.(BridgeServiceServer).FindSymbol(ctx, req.(*FindSymbolRequest)) })
}

func _BridgeService_GetSymbolsOverview_Handler(srv any, ctx context.Context, dec func(any) error, interceptor grpc.UnaryServerInterceptor) (any, error) {
	in := new(GetSymbolsOverviewRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BridgeServiceServer).GetSymbolsOverview(ctx, in)
	}
	info := &grpc.UnaryServerInfo{Server: srv, FullMethod: bridgeServiceName + "GetSymbolsOverview"}
	return interceptor(ctx, in, info, func(ctx context.Context, req any) (any, error) {
		return srv.(BridgeServiceServer).GetSymbolsOverview(ctx, req.(*GetSymbolsOverviewRequest))
	})
}

func _BridgeService_ReplaceSymbolBody_Handler(srv any, ctx context.Context, dec func(any) error, interceptor grpc.UnaryServerInterceptor) (any, error) {
	in := new(ReplaceSymbolBodyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BridgeServiceServer).ReplaceSymbolBody(ctx, in)
	}
	info := &grpc.UnaryServerInfo{Server: srv, FullMethod: bridgeServiceName + "ReplaceSymbolBody"}
	return interceptor(ctx, in, info, func(ctx context.Context, req any) (any, error) {
		return srv.(BridgeServiceServer).ReplaceSymbolBody(ctx, req.(*ReplaceSymbolBodyRequest))
	})
}

func _BridgeService_InsertBeforeSymbol_Handler(srv any, ctx context.Context, dec func(any) error, interceptor grpc.UnaryServerInterceptor) (any, error) {
	in := new(InsertSymbolRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BridgeServiceServer).InsertBeforeSymbol(ctx, in)
	}
	info := &grpc.UnaryServerInfo{Server: srv, FullMethod: bridgeServiceName + "InsertBeforeSymbol"}
	return interceptor(ctx, in, info, func(ctx context.Context, req any) (any, error) {
		return srv.(BridgeServiceServer).InsertBeforeSymbol(ctx, req.(*InsertSymbolRequest))
	})
}

func _BridgeService_InsertAfterSymbol_Handler(srv any, ctx context.Context, dec func(any) error, interceptor grpc.UnaryServerInterceptor) (any, error) {
	in := new(InsertSymbolRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BridgeServiceServer).InsertAfterSymbol(ctx, in)
	}
	info := &grpc.UnaryServerInfo{Server: srv, FullMethod: bridgeServiceName + "InsertAfterSymbol"}
	return interceptor(ctx, in, info, func(ctx context.Context, req any) (any, error) {
		return srv.(BridgeServiceServer).InsertAfterSymbol(ctx, req.(*InsertSymbolRequest))
	})
}

func _BridgeService_RenameSymbol_Handler(srv any, ctx context.Context, dec func(any) error, interceptor grpc.UnaryServerInterceptor) (any, error) {
	in := new(RenameSymbolRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BridgeServiceServer).RenameSymbol(ctx, in)
	}
	info := &grpc.UnaryServerInfo{Server: srv, FullMethod: bridgeServiceName + "RenameSymbol"}
	return interceptor(ctx, in, info, func(ctx context.Context, req any) (any, error) {
		return srv.(BridgeServiceServer).RenameSymbol(ctx, req.(*RenameSymbolRequest))
	})
}

func _BridgeService_KnowledgeSearch_Handler(srv any, ctx context.Context, dec func(any) error, interceptor grpc.UnaryServerInterceptor) (any, error) {
	in := new(KnowledgeSearchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BridgeServiceServer).KnowledgeSearch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{Server: srv, FullMethod: bridgeServiceName + "KnowledgeSearch"}
	return interceptor(ctx, in, info, func(ctx context.Context, req any) (any, error) {
		return srv.(BridgeServiceServer).KnowledgeSearch(ctx, req.(*KnowledgeSearchRequest))
	})
}

func _BridgeService_KnowledgeRecord_Handler(srv any, ctx context.Context, dec func(any) error, interceptor grpc.UnaryServerInterceptor) (any, error) {
	in := new(KnowledgeRecordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BridgeServiceServer).KnowledgeRecord(ctx, in)
	}
	info := &grpc.UnaryServerInfo{Server: srv, FullMethod: bridgeServiceName + "KnowledgeRecord"}
	return interceptor(ctx, in, info, func(ctx context.Context, req any) (any, error) {
		return srv.(BridgeServiceServer).KnowledgeRecord(ctx, req.(*KnowledgeRecordRequest))
	})
}

func _BridgeService_KnowledgeGet_Handler(srv any, ctx context.Context, dec func(any) error, interceptor grpc.UnaryServerInterceptor) (any, error) {
	in := new(KnowledgeGetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BridgeServiceServer).KnowledgeGet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{Server: srv, FullMethod: bridgeServiceName + "KnowledgeGet"}
	return interceptor(ctx, in, info, func(ctx context.Context, req any) (any, error) {
		return srv.(BridgeServiceServer).KnowledgeGet(ctx, req.(*KnowledgeGetRequest))
	})
}

func _BridgeService_GPUStatus_Handler(srv any, ctx context.Context, dec func(any) error, interceptor grpc.UnaryServerInterceptor) (any, error) {
	in := new(GPUStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BridgeServiceServer).GPUStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{Server: srv, FullMethod: bridgeServiceName + "GPUStatus"}
	return interceptor(ctx, in, info, func(ctx context.Context, req any) (any, error) { return srv.(BridgeServiceServer).GPUStatus(ctx, req.(*GPUStatusRequest)) })
}

func _BridgeService_JobSubmit_Handler(srv any, ctx context.Context, dec func(any) error, interceptor grpc.UnaryServerInterceptor) (any, error) {
	in := new(JobSubmitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BridgeServiceServer).JobSubmit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{Server: srv, FullMethod: bridgeServiceName + "JobSubmit"}
	return interceptor(ctx, in, info, func(ctx context.Context, req any) (any, error) { return srv.(BridgeServiceServer).JobSubmit(ctx, req.(*JobSubmitRequest)) })
}
