// Code generated by hand (stub). DO NOT EDIT.
// This file provides stub types that match the protobuf-generated API.
// Run `make proto-gen` to replace with actual generated code.

package pb

// =============================================================================
// Core messages
// =============================================================================

type GetStateRequest struct{}

type GetStateResponse struct {
	State        string `protobuf:"bytes,1,opt,name=state,proto3" json:"state,omitempty"`
	ProjectName  string `protobuf:"bytes,2,opt,name=project_name,json=projectName,proto3" json:"project_name,omitempty"`
	TotalTasks   int32  `protobuf:"varint,3,opt,name=total_tasks,json=totalTasks,proto3" json:"total_tasks,omitempty"`
	PendingTasks int32  `protobuf:"varint,4,opt,name=pending_tasks,json=pendingTasks,proto3" json:"pending_tasks,omitempty"`
	DoneTasks    int32  `protobuf:"varint,5,opt,name=done_tasks,json=doneTasks,proto3" json:"done_tasks,omitempty"`
	BlockedTasks int32  `protobuf:"varint,6,opt,name=blocked_tasks,json=blockedTasks,proto3" json:"blocked_tasks,omitempty"`
}

type TransitionStateRequest struct {
	Event string `protobuf:"bytes,1,opt,name=event,proto3" json:"event,omitempty"`
}

type TransitionStateResponse struct {
	Success  bool   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	NewState string `protobuf:"bytes,2,opt,name=new_state,json=newState,proto3" json:"new_state,omitempty"`
	Error    string `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
}

type GetTaskRequest struct {
	WorkerId string `protobuf:"bytes,1,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
}

type GetTaskResponse struct {
	HasTask     bool     `protobuf:"varint,1,opt,name=has_task,json=hasTask,proto3" json:"has_task,omitempty"`
	TaskId      string   `protobuf:"bytes,2,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Title       string   `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Scope       string   `protobuf:"bytes,4,opt,name=scope,proto3" json:"scope,omitempty"`
	Dod         string   `protobuf:"bytes,5,opt,name=dod,proto3" json:"dod,omitempty"`
	Validations []string `protobuf:"bytes,6,rep,name=validations,proto3" json:"validations,omitempty"`
	Branch      string   `protobuf:"bytes,7,opt,name=branch,proto3" json:"branch,omitempty"`
	Domain      string   `protobuf:"bytes,8,opt,name=domain,proto3" json:"domain,omitempty"`
}

type SubmitTaskRequest struct {
	TaskId            string          `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	WorkerId          string          `protobuf:"bytes,2,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	CommitSha         string          `protobuf:"bytes,3,opt,name=commit_sha,json=commitSha,proto3" json:"commit_sha,omitempty"`
	ValidationResults map[string]bool `protobuf:"bytes,4,rep,name=validation_results,json=validationResults,proto3" json:"validation_results,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
}

type SubmitTaskResponse struct {
	Success    bool   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	NextAction string `protobuf:"bytes,2,opt,name=next_action,json=nextAction,proto3" json:"next_action,omitempty"`
	Error      string `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
}

type RunValidationRequest struct {
	Names []string `protobuf:"bytes,1,rep,name=names,proto3" json:"names,omitempty"`
}

type ValidationResult struct {
	Name   string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Passed bool   `protobuf:"varint,2,opt,name=passed,proto3" json:"passed,omitempty"`
	Output string `protobuf:"bytes,3,opt,name=output,proto3" json:"output,omitempty"`
}

type RunValidationResponse struct {
	AllPassed bool                `protobuf:"varint,1,opt,name=all_passed,json=allPassed,proto3" json:"all_passed,omitempty"`
	Results   []*ValidationResult `protobuf:"bytes,2,rep,name=results,proto3" json:"results,omitempty"`
}

// =============================================================================
// LSP messages
// =============================================================================

type FindSymbolRequest struct {
	Name     string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	FilePath string `protobuf:"bytes,2,opt,name=file_path,json=filePath,proto3" json:"file_path,omitempty"`
	Kind     string `protobuf:"bytes,3,opt,name=kind,proto3" json:"kind,omitempty"`
}

type SymbolLocation struct {
	FilePath  string `protobuf:"bytes,1,opt,name=file_path,json=filePath,proto3" json:"file_path,omitempty"`
	Name      string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Kind      string `protobuf:"bytes,3,opt,name=kind,proto3" json:"kind,omitempty"`
	StartLine int32  `protobuf:"varint,4,opt,name=start_line,json=startLine,proto3" json:"start_line,omitempty"`
	StartCol  int32  `protobuf:"varint,5,opt,name=start_col,json=startCol,proto3" json:"start_col,omitempty"`
	EndLine   int32  `protobuf:"varint,6,opt,name=end_line,json=endLine,proto3" json:"end_line,omitempty"`
	EndCol    int32  `protobuf:"varint,7,opt,name=end_col,json=endCol,proto3" json:"end_col,omitempty"`
	Container string `protobuf:"bytes,8,opt,name=container,proto3" json:"container,omitempty"`
}

type FindSymbolResponse struct {
	Symbols []*SymbolLocation `protobuf:"bytes,1,rep,name=symbols,proto3" json:"symbols,omitempty"`
}

type GetSymbolsOverviewRequest struct {
	FilePath string `protobuf:"bytes,1,opt,name=file_path,json=filePath,proto3" json:"file_path,omitempty"`
}

type GetSymbolsOverviewResponse struct {
	Symbols []*SymbolLocation `protobuf:"bytes,1,rep,name=symbols,proto3" json:"symbols,omitempty"`
}

type ReplaceSymbolBodyRequest struct {
	FilePath   string `protobuf:"bytes,1,opt,name=file_path,json=filePath,proto3" json:"file_path,omitempty"`
	SymbolName string `protobuf:"bytes,2,opt,name=symbol_name,json=symbolName,proto3" json:"symbol_name,omitempty"`
	NewBody    string `protobuf:"bytes,3,opt,name=new_body,json=newBody,proto3" json:"new_body,omitempty"`
}

type ReplaceSymbolBodyResponse struct {
	Success      bool   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error        string `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	LinesChanged int32  `protobuf:"varint,3,opt,name=lines_changed,json=linesChanged,proto3" json:"lines_changed,omitempty"`
}

type InsertSymbolRequest struct {
	FilePath   string `protobuf:"bytes,1,opt,name=file_path,json=filePath,proto3" json:"file_path,omitempty"`
	SymbolName string `protobuf:"bytes,2,opt,name=symbol_name,json=symbolName,proto3" json:"symbol_name,omitempty"`
	Content    string `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
}

type InsertSymbolResponse struct {
	Success bool   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error   string `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
}

type RenameSymbolRequest struct {
	FilePath string `protobuf:"bytes,1,opt,name=file_path,json=filePath,proto3" json:"file_path,omitempty"`
	OldName  string `protobuf:"bytes,2,opt,name=old_name,json=oldName,proto3" json:"old_name,omitempty"`
	NewName  string `protobuf:"bytes,3,opt,name=new_name,json=newName,proto3" json:"new_name,omitempty"`
}

type RenameSymbolResponse struct {
	Success           bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error             string   `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	ModifiedFiles     []string `protobuf:"bytes,3,rep,name=modified_files,json=modifiedFiles,proto3" json:"modified_files,omitempty"`
	ReferencesUpdated int32    `protobuf:"varint,4,opt,name=references_updated,json=referencesUpdated,proto3" json:"references_updated,omitempty"`
}

// =============================================================================
// Knowledge Store messages
// =============================================================================

type KnowledgeSearchRequest struct {
	Query              string `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	DocType            string `protobuf:"bytes,2,opt,name=doc_type,json=docType,proto3" json:"doc_type,omitempty"`
	Limit              int32  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	MetadataFilterJson string `protobuf:"bytes,4,opt,name=metadata_filter_json,json=metadataFilterJson,proto3" json:"metadata_filter_json,omitempty"`
}

type KnowledgeDocument struct {
	Slug         string  `protobuf:"bytes,1,opt,name=slug,proto3" json:"slug,omitempty"`
	DocType      string  `protobuf:"bytes,2,opt,name=doc_type,json=docType,proto3" json:"doc_type,omitempty"`
	Title        string  `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Content      string  `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	MetadataJson string  `protobuf:"bytes,5,opt,name=metadata_json,json=metadataJson,proto3" json:"metadata_json,omitempty"`
	CreatedAt    string  `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt    string  `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	Score        float32 `protobuf:"fixed32,8,opt,name=score,proto3" json:"score,omitempty"`
}

type KnowledgeSearchResponse struct {
	Documents  []*KnowledgeDocument `protobuf:"bytes,1,rep,name=documents,proto3" json:"documents,omitempty"`
	TotalCount int32                `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
}

type KnowledgeRecordRequest struct {
	DocType      string   `protobuf:"bytes,1,opt,name=doc_type,json=docType,proto3" json:"doc_type,omitempty"`
	Title        string   `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Content      string   `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	MetadataJson string   `protobuf:"bytes,4,opt,name=metadata_json,json=metadataJson,proto3" json:"metadata_json,omitempty"`
	Tags         []string `protobuf:"bytes,5,rep,name=tags,proto3" json:"tags,omitempty"`
}

type KnowledgeRecordResponse struct {
	Success bool   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Slug    string `protobuf:"bytes,2,opt,name=slug,proto3" json:"slug,omitempty"`
	Error   string `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
}

type KnowledgeGetRequest struct {
	Slug string `protobuf:"bytes,1,opt,name=slug,proto3" json:"slug,omitempty"`
}

type KnowledgeGetResponse struct {
	Found    bool               `protobuf:"varint,1,opt,name=found,proto3" json:"found,omitempty"`
	Document *KnowledgeDocument `protobuf:"bytes,2,opt,name=document,proto3" json:"document,omitempty"`
}

// =============================================================================
// GPU / Job messages
// =============================================================================

type GPUStatusRequest struct{}

type GPUDevice struct {
	Index          int32   `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	Name           string  `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	MemoryTotalMb  int64   `protobuf:"varint,3,opt,name=memory_total_mb,json=memoryTotalMb,proto3" json:"memory_total_mb,omitempty"`
	MemoryUsedMb   int64   `protobuf:"varint,4,opt,name=memory_used_mb,json=memoryUsedMb,proto3" json:"memory_used_mb,omitempty"`
	MemoryFreeMb   int64   `protobuf:"varint,5,opt,name=memory_free_mb,json=memoryFreeMb,proto3" json:"memory_free_mb,omitempty"`
	UtilizationPct float32 `protobuf:"fixed32,6,opt,name=utilization_pct,json=utilizationPct,proto3" json:"utilization_pct,omitempty"`
	Backend        string  `protobuf:"bytes,7,opt,name=backend,proto3" json:"backend,omitempty"`
}

type GPUStatusResponse struct {
	Available bool         `protobuf:"varint,1,opt,name=available,proto3" json:"available,omitempty"`
	Backend   string       `protobuf:"bytes,2,opt,name=backend,proto3" json:"backend,omitempty"`
	Devices   []*GPUDevice `protobuf:"bytes,3,rep,name=devices,proto3" json:"devices,omitempty"`
}

type JobSubmitRequest struct {
	Name          string            `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Command       string            `protobuf:"bytes,2,opt,name=command,proto3" json:"command,omitempty"`
	WorkingDir    string            `protobuf:"bytes,3,opt,name=working_dir,json=workingDir,proto3" json:"working_dir,omitempty"`
	Env           map[string]string `protobuf:"bytes,4,rep,name=env,proto3" json:"env,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	ResourcesJson string            `protobuf:"bytes,5,opt,name=resources_json,json=resourcesJson,proto3" json:"resources_json,omitempty"`
	Priority      int32             `protobuf:"varint,6,opt,name=priority,proto3" json:"priority,omitempty"`
}

type JobSubmitResponse struct {
	Success bool   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	JobId   string `protobuf:"bytes,2,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	Error   string `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	Status  string `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
}
