// Code generated by hand (stub). DO NOT EDIT.
// This file provides a JSON codec for gRPC that works with stub types
// that don't implement the full proto.Message interface.
// Run `make proto-gen` to replace pb/ with actual generated code.

package pb

import (
	"encoding/json"
	"fmt"

	"google.golang.org/grpc/encoding"
)

func init() {
	encoding.RegisterCodec(JSONCodec{})
}

// JSONCodec implements encoding.CodecV2 using JSON serialization.
// This is used as a fallback when stub types don't implement proto.Message.
type JSONCodec struct{}

// Marshal serializes v to JSON bytes.
func (JSONCodec) Marshal(v any) ([]byte, error) {
	return json.Marshal(v)
}

// Unmarshal deserializes JSON bytes into v.
func (JSONCodec) Unmarshal(data []byte, v any) error {
	return json.Unmarshal(data, v)
}

// Name returns the codec name. Returning "proto" overrides the default
// protobuf codec so that gRPC uses JSON for stub types.
func (JSONCodec) Name() string {
	return "proto"
}

// String returns a debug representation.
func (JSONCodec) String() string {
	return fmt.Sprintf("JSONCodec{}")
}
