#!/bin/bash
# =============================================================================
# C4 Installer
# =============================================================================
#
# Usage:
#   git clone https://github.com/USER/c4.git && cd c4 && ./install.sh
#
# What it does:
#   1. Install dependencies (uv sync)
#   2. Save C4 install path (~/.c4-install-path)
#   3. Create global 'c4' command (~/.local/bin/c4)
#   4. Install /c4-* slash commands (~/.claude/commands/)
#   5. Install security & stop hooks (~/.claude/hooks/)
#   6. Register hooks in Claude settings
#
# =============================================================================

set -e

echo "🚀 Installing C4..."
echo ""

# Determine C4 directory
C4_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# Validate
if [[ ! -f "$C4_DIR/c4/cli.py" ]]; then
    echo "❌ Error: Not a valid C4 installation"
    exit 1
fi

echo "📁 C4 directory: $C4_DIR"
echo ""

# =============================================================================
# Step 1: Install dependencies
# =============================================================================
echo "1️⃣  Installing dependencies..."
if command -v uv &> /dev/null; then
    (cd "$C4_DIR" && uv sync --quiet)
    echo "   ✅ Dependencies installed"
else
    echo "❌ Error: uv not found. Install it first:"
    echo "   curl -LsSf https://astral.sh/uv/install.sh | sh"
    exit 1
fi

# =============================================================================
# Step 2: Save install path
# =============================================================================
echo "2️⃣  Saving install path..."
echo "$C4_DIR" > ~/.c4-install-path
echo "   → ~/.c4-install-path"

# =============================================================================
# Step 3: Create global 'c4' command
# =============================================================================
echo "3️⃣  Creating global 'c4' command..."

BIN_DIR="$HOME/.local/bin"
mkdir -p "$BIN_DIR"

cat > "$BIN_DIR/c4" << EOF
#!/bin/bash
# C4 CLI - Auto-generated by install.sh
# Pass current directory to c4 (uv --directory changes cwd)
exec uv run --directory "$C4_DIR" c4 --path "\$(pwd)" "\$@"
EOF

chmod +x "$BIN_DIR/c4"
echo "   → $BIN_DIR/c4"

# =============================================================================
# Step 4: Install /c4-* slash commands globally
# =============================================================================
echo "4️⃣  Installing Claude Code slash commands..."

CLAUDE_COMMANDS="$HOME/.claude/commands"
mkdir -p "$CLAUDE_COMMANDS"

count=0
for cmd in "$C4_DIR/.claude/commands"/c4-*.md; do
    if [[ -f "$cmd" ]]; then
        cp "$cmd" "$CLAUDE_COMMANDS/"
        echo "   → $(basename "$cmd")"
        ((count++))
    fi
done
echo "   ✅ $count commands installed"

# =============================================================================
# Step 5: Install hooks
# =============================================================================
echo "5️⃣  Installing Claude Code hooks..."

HOOKS_DIR="$HOME/.claude/hooks"
mkdir -p "$HOOKS_DIR"

# Stop hook (inline)
cat > "$HOOKS_DIR/stop.sh" << 'HOOK'
#!/bin/bash
# Check for C4 project (SQLite or legacy JSON)
if [[ ! -f ".c4/c4.db" ]] && [[ ! -f ".c4/state.json" ]]; then exit 0; fi
result=$(python3 ~/.claude/hooks/c4-stop-hook.py 2>/dev/null)
if [[ $? -eq 2 ]]; then
    echo "{\"decision\":\"block\",\"reason\":\"$result\",\"instructions\":\"Continue with /c4-run\"}"
    exit 2
fi
exit 0
HOOK
chmod +x "$HOOKS_DIR/stop.sh"
echo "   → stop.sh"

# Copy template scripts
for script in c4-stop-hook.py c4-bash-security-hook.sh; do
    if [[ -f "$C4_DIR/templates/$script" ]]; then
        cp "$C4_DIR/templates/$script" "$HOOKS_DIR/"
        chmod +x "$HOOKS_DIR/$script"
        echo "   → $script"
    fi
done

# =============================================================================
# Step 6: Register hooks in settings
# =============================================================================
echo "6️⃣  Registering hooks..."

python3 << 'PYTHON'
import json
from pathlib import Path

settings_path = Path.home() / ".claude" / "settings.json"
settings_path.parent.mkdir(parents=True, exist_ok=True)

settings = json.loads(settings_path.read_text()) if settings_path.exists() else {}

if "hooks" not in settings:
    settings["hooks"] = {}
if "PreToolUse" not in settings["hooks"]:
    settings["hooks"]["PreToolUse"] = []

bash_hook = {
    "matcher": "Bash",
    "hooks": [{"type": "command", "command": "~/.claude/hooks/c4-bash-security-hook.sh"}]
}

settings["hooks"]["PreToolUse"] = [
    h for h in settings["hooks"]["PreToolUse"] if h.get("matcher") != "Bash"
]
settings["hooks"]["PreToolUse"].append(bash_hook)

settings_path.write_text(json.dumps(settings, indent=2))
PYTHON
echo "   → ~/.claude/settings.json"

# =============================================================================
# Done!
# =============================================================================
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "✅ C4 installed successfully!"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "📌 Usage:"
echo ""
echo "   Terminal:"
echo "     c4 init --path /path/to/project"
echo "     c4 status"
echo ""
echo "   Claude Code:"
echo "     /c4-init      # Initialize project"
echo "     /c4-plan      # Parse docs & create tasks"
echo "     /c4-run       # Start execution"
echo "     /c4-status    # Check status"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"

# Auto-setup PATH if needed
if [[ ":$PATH:" != *":$BIN_DIR:"* ]]; then
    SHELL_RC=""
    if [[ -n "$ZSH_VERSION" ]] || [[ "$SHELL" == */zsh ]]; then
        SHELL_RC="$HOME/.zshrc"
    elif [[ -n "$BASH_VERSION" ]] || [[ "$SHELL" == */bash ]]; then
        SHELL_RC="$HOME/.bashrc"
    fi

    if [[ -n "$SHELL_RC" ]] && ! grep -q '.local/bin' "$SHELL_RC" 2>/dev/null; then
        echo "" >> "$SHELL_RC"
        echo '# C4 CLI' >> "$SHELL_RC"
        echo 'export PATH="$HOME/.local/bin:$PATH"' >> "$SHELL_RC"
        echo ""
        echo "✅ Added ~/.local/bin to PATH in $SHELL_RC"
        echo "   Run: source $SHELL_RC"
    fi
fi

echo ""
echo "🔄 Restart Claude Code to activate slash commands"
echo ""
