// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: eventbus.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Event struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`     // e.g. "drive.uploaded", "task.completed"
	Source        string                 `protobuf:"bytes,3,opt,name=source,proto3" json:"source,omitempty"` // e.g. "c4.drive", "c4.core"
	Data          []byte                 `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`     // JSON payload
	ProjectId     string                 `protobuf:"bytes,5,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	TimestampMs   int64                  `protobuf:"varint,6,opt,name=timestamp_ms,json=timestampMs,proto3" json:"timestamp_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_eventbus_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_eventbus_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_eventbus_proto_rawDescGZIP(), []int{0}
}

func (x *Event) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Event) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Event) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *Event) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *Event) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *Event) GetTimestampMs() int64 {
	if x != nil {
		return x.TimestampMs
	}
	return 0
}

type PublishResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventId       string                 `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	Ok            bool                   `protobuf:"varint,2,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishResponse) Reset() {
	*x = PublishResponse{}
	mi := &file_eventbus_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishResponse) ProtoMessage() {}

func (x *PublishResponse) ProtoReflect() protoreflect.Message {
	mi := &file_eventbus_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishResponse.ProtoReflect.Descriptor instead.
func (*PublishResponse) Descriptor() ([]byte, []int) {
	return file_eventbus_proto_rawDescGZIP(), []int{1}
}

func (x *PublishResponse) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *PublishResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

type SubscribeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventPattern  string                 `protobuf:"bytes,1,opt,name=event_pattern,json=eventPattern,proto3" json:"event_pattern,omitempty"` // "drive.*" or "drive.uploaded"
	ProjectId     string                 `protobuf:"bytes,2,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`          // optional project filter
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeRequest) Reset() {
	*x = SubscribeRequest{}
	mi := &file_eventbus_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeRequest) ProtoMessage() {}

func (x *SubscribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_eventbus_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeRequest.ProtoReflect.Descriptor instead.
func (*SubscribeRequest) Descriptor() ([]byte, []int) {
	return file_eventbus_proto_rawDescGZIP(), []int{2}
}

func (x *SubscribeRequest) GetEventPattern() string {
	if x != nil {
		return x.EventPattern
	}
	return ""
}

func (x *SubscribeRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

type ListEventsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	SinceMs       int64                  `protobuf:"varint,3,opt,name=since_ms,json=sinceMs,proto3" json:"since_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListEventsRequest) Reset() {
	*x = ListEventsRequest{}
	mi := &file_eventbus_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListEventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListEventsRequest) ProtoMessage() {}

func (x *ListEventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_eventbus_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListEventsRequest.ProtoReflect.Descriptor instead.
func (*ListEventsRequest) Descriptor() ([]byte, []int) {
	return file_eventbus_proto_rawDescGZIP(), []int{3}
}

func (x *ListEventsRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ListEventsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListEventsRequest) GetSinceMs() int64 {
	if x != nil {
		return x.SinceMs
	}
	return 0
}

type ListEventsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Events        []*Event               `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListEventsResponse) Reset() {
	*x = ListEventsResponse{}
	mi := &file_eventbus_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListEventsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListEventsResponse) ProtoMessage() {}

func (x *ListEventsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_eventbus_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListEventsResponse.ProtoReflect.Descriptor instead.
func (*ListEventsResponse) Descriptor() ([]byte, []int) {
	return file_eventbus_proto_rawDescGZIP(), []int{4}
}

func (x *ListEventsResponse) GetEvents() []*Event {
	if x != nil {
		return x.Events
	}
	return nil
}

func (x *ListEventsResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type Rule struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	EventPattern  string                 `protobuf:"bytes,3,opt,name=event_pattern,json=eventPattern,proto3" json:"event_pattern,omitempty"` // "drive.uploaded"
	FilterJson    string                 `protobuf:"bytes,4,opt,name=filter_json,json=filterJson,proto3" json:"filter_json,omitempty"`       // e.g. {"content_type": "application/pdf"}
	ActionType    string                 `protobuf:"bytes,5,opt,name=action_type,json=actionType,proto3" json:"action_type,omitempty"`       // "rpc", "webhook", "log"
	ActionConfig  string                 `protobuf:"bytes,6,opt,name=action_config,json=actionConfig,proto3" json:"action_config,omitempty"` // JSON: action-specific config
	Enabled       bool                   `protobuf:"varint,7,opt,name=enabled,proto3" json:"enabled,omitempty"`
	Priority      int32                  `protobuf:"varint,8,opt,name=priority,proto3" json:"priority,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Rule) Reset() {
	*x = Rule{}
	mi := &file_eventbus_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Rule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Rule) ProtoMessage() {}

func (x *Rule) ProtoReflect() protoreflect.Message {
	mi := &file_eventbus_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Rule.ProtoReflect.Descriptor instead.
func (*Rule) Descriptor() ([]byte, []int) {
	return file_eventbus_proto_rawDescGZIP(), []int{5}
}

func (x *Rule) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Rule) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Rule) GetEventPattern() string {
	if x != nil {
		return x.EventPattern
	}
	return ""
}

func (x *Rule) GetFilterJson() string {
	if x != nil {
		return x.FilterJson
	}
	return ""
}

func (x *Rule) GetActionType() string {
	if x != nil {
		return x.ActionType
	}
	return ""
}

func (x *Rule) GetActionConfig() string {
	if x != nil {
		return x.ActionConfig
	}
	return ""
}

func (x *Rule) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *Rule) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

type RuleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RuleId        string                 `protobuf:"bytes,1,opt,name=rule_id,json=ruleId,proto3" json:"rule_id,omitempty"`
	Ok            bool                   `protobuf:"varint,2,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RuleResponse) Reset() {
	*x = RuleResponse{}
	mi := &file_eventbus_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RuleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RuleResponse) ProtoMessage() {}

func (x *RuleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_eventbus_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RuleResponse.ProtoReflect.Descriptor instead.
func (*RuleResponse) Descriptor() ([]byte, []int) {
	return file_eventbus_proto_rawDescGZIP(), []int{6}
}

func (x *RuleResponse) GetRuleId() string {
	if x != nil {
		return x.RuleId
	}
	return ""
}

func (x *RuleResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

type ListRulesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRulesRequest) Reset() {
	*x = ListRulesRequest{}
	mi := &file_eventbus_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRulesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRulesRequest) ProtoMessage() {}

func (x *ListRulesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_eventbus_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRulesRequest.ProtoReflect.Descriptor instead.
func (*ListRulesRequest) Descriptor() ([]byte, []int) {
	return file_eventbus_proto_rawDescGZIP(), []int{7}
}

type ListRulesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rules         []*Rule                `protobuf:"bytes,1,rep,name=rules,proto3" json:"rules,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRulesResponse) Reset() {
	*x = ListRulesResponse{}
	mi := &file_eventbus_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRulesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRulesResponse) ProtoMessage() {}

func (x *ListRulesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_eventbus_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRulesResponse.ProtoReflect.Descriptor instead.
func (*ListRulesResponse) Descriptor() ([]byte, []int) {
	return file_eventbus_proto_rawDescGZIP(), []int{8}
}

func (x *ListRulesResponse) GetRules() []*Rule {
	if x != nil {
		return x.Rules
	}
	return nil
}

type RemoveRuleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"` // alternative: remove by name
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveRuleRequest) Reset() {
	*x = RemoveRuleRequest{}
	mi := &file_eventbus_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveRuleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveRuleRequest) ProtoMessage() {}

func (x *RemoveRuleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_eventbus_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveRuleRequest.ProtoReflect.Descriptor instead.
func (*RemoveRuleRequest) Descriptor() ([]byte, []int) {
	return file_eventbus_proto_rawDescGZIP(), []int{9}
}

func (x *RemoveRuleRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RemoveRuleRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

var File_eventbus_proto protoreflect.FileDescriptor

const file_eventbus_proto_rawDesc = "" +
	"\n" +
	"\x0eeventbus.proto\x12\beventbus\"\x99\x01\n" +
	"\x05Event\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x16\n" +
	"\x06source\x18\x03 \x01(\tR\x06source\x12\x12\n" +
	"\x04data\x18\x04 \x01(\fR\x04data\x12\x1d\n" +
	"\n" +
	"project_id\x18\x05 \x01(\tR\tprojectId\x12!\n" +
	"\ftimestamp_ms\x18\x06 \x01(\x03R\vtimestampMs\"<\n" +
	"\x0fPublishResponse\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\x12\x0e\n" +
	"\x02ok\x18\x02 \x01(\bR\x02ok\"V\n" +
	"\x10SubscribeRequest\x12#\n" +
	"\revent_pattern\x18\x01 \x01(\tR\feventPattern\x12\x1d\n" +
	"\n" +
	"project_id\x18\x02 \x01(\tR\tprojectId\"X\n" +
	"\x11ListEventsRequest\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12\x19\n" +
	"\bsince_ms\x18\x03 \x01(\x03R\asinceMs\"S\n" +
	"\x12ListEventsResponse\x12'\n" +
	"\x06events\x18\x01 \x03(\v2\x0f.eventbus.EventR\x06events\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\"\xec\x01\n" +
	"\x04Rule\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12#\n" +
	"\revent_pattern\x18\x03 \x01(\tR\feventPattern\x12\x1f\n" +
	"\vfilter_json\x18\x04 \x01(\tR\n" +
	"filterJson\x12\x1f\n" +
	"\vaction_type\x18\x05 \x01(\tR\n" +
	"actionType\x12#\n" +
	"\raction_config\x18\x06 \x01(\tR\factionConfig\x12\x18\n" +
	"\aenabled\x18\a \x01(\bR\aenabled\x12\x1a\n" +
	"\bpriority\x18\b \x01(\x05R\bpriority\"7\n" +
	"\fRuleResponse\x12\x17\n" +
	"\arule_id\x18\x01 \x01(\tR\x06ruleId\x12\x0e\n" +
	"\x02ok\x18\x02 \x01(\bR\x02ok\"\x12\n" +
	"\x10ListRulesRequest\"9\n" +
	"\x11ListRulesResponse\x12$\n" +
	"\x05rules\x18\x01 \x03(\v2\x0e.eventbus.RuleR\x05rules\"7\n" +
	"\x11RemoveRuleRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name2\x82\x03\n" +
	"\bEventBus\x125\n" +
	"\aPublish\x12\x0f.eventbus.Event\x1a\x19.eventbus.PublishResponse\x12:\n" +
	"\tSubscribe\x12\x1a.eventbus.SubscribeRequest\x1a\x0f.eventbus.Event0\x01\x12G\n" +
	"\n" +
	"ListEvents\x12\x1b.eventbus.ListEventsRequest\x1a\x1c.eventbus.ListEventsResponse\x121\n" +
	"\aAddRule\x12\x0e.eventbus.Rule\x1a\x16.eventbus.RuleResponse\x12D\n" +
	"\tListRules\x12\x1a.eventbus.ListRulesRequest\x1a\x1b.eventbus.ListRulesResponse\x12A\n" +
	"\n" +
	"RemoveRule\x12\x1b.eventbus.RemoveRuleRequest\x1a\x16.eventbus.RuleResponseB2Z0github.com/changmin/c4-core/internal/eventbus/pbb\x06proto3"

var (
	file_eventbus_proto_rawDescOnce sync.Once
	file_eventbus_proto_rawDescData []byte
)

func file_eventbus_proto_rawDescGZIP() []byte {
	file_eventbus_proto_rawDescOnce.Do(func() {
		file_eventbus_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_eventbus_proto_rawDesc), len(file_eventbus_proto_rawDesc)))
	})
	return file_eventbus_proto_rawDescData
}

var file_eventbus_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_eventbus_proto_goTypes = []any{
	(*Event)(nil),              // 0: eventbus.Event
	(*PublishResponse)(nil),    // 1: eventbus.PublishResponse
	(*SubscribeRequest)(nil),   // 2: eventbus.SubscribeRequest
	(*ListEventsRequest)(nil),  // 3: eventbus.ListEventsRequest
	(*ListEventsResponse)(nil), // 4: eventbus.ListEventsResponse
	(*Rule)(nil),               // 5: eventbus.Rule
	(*RuleResponse)(nil),       // 6: eventbus.RuleResponse
	(*ListRulesRequest)(nil),   // 7: eventbus.ListRulesRequest
	(*ListRulesResponse)(nil),  // 8: eventbus.ListRulesResponse
	(*RemoveRuleRequest)(nil),  // 9: eventbus.RemoveRuleRequest
}
var file_eventbus_proto_depIdxs = []int32{
	0, // 0: eventbus.ListEventsResponse.events:type_name -> eventbus.Event
	5, // 1: eventbus.ListRulesResponse.rules:type_name -> eventbus.Rule
	0, // 2: eventbus.EventBus.Publish:input_type -> eventbus.Event
	2, // 3: eventbus.EventBus.Subscribe:input_type -> eventbus.SubscribeRequest
	3, // 4: eventbus.EventBus.ListEvents:input_type -> eventbus.ListEventsRequest
	5, // 5: eventbus.EventBus.AddRule:input_type -> eventbus.Rule
	7, // 6: eventbus.EventBus.ListRules:input_type -> eventbus.ListRulesRequest
	9, // 7: eventbus.EventBus.RemoveRule:input_type -> eventbus.RemoveRuleRequest
	1, // 8: eventbus.EventBus.Publish:output_type -> eventbus.PublishResponse
	0, // 9: eventbus.EventBus.Subscribe:output_type -> eventbus.Event
	4, // 10: eventbus.EventBus.ListEvents:output_type -> eventbus.ListEventsResponse
	6, // 11: eventbus.EventBus.AddRule:output_type -> eventbus.RuleResponse
	8, // 12: eventbus.EventBus.ListRules:output_type -> eventbus.ListRulesResponse
	6, // 13: eventbus.EventBus.RemoveRule:output_type -> eventbus.RuleResponse
	8, // [8:14] is the sub-list for method output_type
	2, // [2:8] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_eventbus_proto_init() }
func file_eventbus_proto_init() {
	if File_eventbus_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_eventbus_proto_rawDesc), len(file_eventbus_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_eventbus_proto_goTypes,
		DependencyIndexes: file_eventbus_proto_depIdxs,
		MessageInfos:      file_eventbus_proto_msgTypes,
	}.Build()
	File_eventbus_proto = out.File
	file_eventbus_proto_goTypes = nil
	file_eventbus_proto_depIdxs = nil
}
