#!/bin/bash
# PI Lab Bash Security Hook (PreToolUse)
# Reviews Bash commands for safety — blocks dangerous, auto-approves safe ones.
#
# Exit codes:
#   0 - Allow command
#   2 - Block command
#
# Configuration: .c4/hook-config.json (SSOT, generated by MCP server)
# Fallback: hardcoded safe patterns

INPUT=$(cat)
COMMAND=$(echo "$INPUT" | jq -r '.tool_input.command // empty' 2>/dev/null)
[[ -z "$COMMAND" ]] && exit 0

# Find project root
_find_root() {
    local dir="${CLAUDE_PROJECT_DIR:-$PWD}"
    while [[ "$dir" != "/" ]] && [[ -n "$dir" ]]; do
        [[ -d "$dir/.c4" ]] && echo "$dir" && return 0
        dir="${dir%/*}"
    done
    return 1
}
PROJECT_ROOT=$(_find_root) || exit 0

# Load config
HOOK_CONFIG="${PROJECT_ROOT}/.c4/hook-config.json"
ALLOW_PATTERNS=()
BLOCK_PATTERNS=()
PERMISSION_MODE="hook"
AUTO_APPROVE="true"

if [[ -f "$HOOK_CONFIG" ]] && command -v jq &>/dev/null; then
    [[ "$(jq -r '.enabled // true' "$HOOK_CONFIG")" == "false" ]] && exit 0
    PERMISSION_MODE=$(jq -r '.mode // "hook"' "$HOOK_CONFIG")
    AUTO_APPROVE=$(jq -r '.auto_approve // true' "$HOOK_CONFIG")
    while IFS= read -r p; do [[ -n "$p" ]] && ALLOW_PATTERNS+=("$p"); done < <(jq -r '.allow_patterns[]? // empty' "$HOOK_CONFIG")
    while IFS= read -r p; do [[ -n "$p" ]] && BLOCK_PATTERNS+=("$p"); done < <(jq -r '.block_patterns[]? // empty' "$HOOK_CONFIG")
fi

# Default safe patterns (fallback)
if [[ ${#ALLOW_PATTERNS[@]} -eq 0 ]]; then
    ALLOW_PATTERNS=(
        "^git (log|show|diff|status|branch|tag|remote|stash list|ls-files|blame)( |$)"
        "^go (build|test|vet|run|env|list|mod)( |$)"
        "^uv (run|sync|pip list|pip show|lock|python)( |$)"
        "^(ls|ll|la|cat|head|tail|wc|stat)( |$)"
        "^find \\. "
        "^(grep|rg) "
        "^(echo|pwd|which|env|printenv|date|uname|whoami)( |$)"
        "^(cargo|rustc) (build|test|check|clippy)( |$)"
        "^pnpm (build|test|lint|install|dev)( |$)"
        "^cq (status|doctor|mcp|version|help)( |$)"
        "^sqlite3 "
    )
fi

# Helpers
_emit_allow() {
    local reason="${1:-Safe command}"
    if [[ "$AUTO_APPROVE" == "true" ]]; then
        echo "{\"hookSpecificOutput\":{\"hookEventName\":\"PreToolUse\",\"permissionDecision\":\"allow\",\"permissionDecisionReason\":\"$reason\"}}"
    fi
    exit 0
}

_emit_deny() {
    echo "{\"hookSpecificOutput\":{\"hookEventName\":\"PreToolUse\",\"permissionDecision\":\"deny\",\"permissionDecisionReason\":\"$1\"}}"
    exit 2
}

# Whitelist check
for pattern in "${ALLOW_PATTERNS[@]}"; do
    [[ "$COMMAND" =~ $pattern ]] && _emit_allow "Whitelist match"
done

# Block patterns
for pattern in "${BLOCK_PATTERNS[@]}"; do
    [[ "$COMMAND" =~ $pattern ]] && _emit_deny "Blocked: matches '$pattern'"
done

# Hardcoded dangerous patterns
[[ "$COMMAND" =~ rm[[:space:]]+-rf?[[:space:]]+/ ]] && _emit_deny "Recursive delete of system directory"
[[ "$COMMAND" =~ rm[[:space:]]+-rf?[[:space:]]+~ ]] && _emit_deny "Recursive delete of home directory"
[[ "$COMMAND" =~ sudo[[:space:]]+(rm|chmod|chown|mkfs|dd) ]] && _emit_deny "sudo with destructive command"
[[ "$COMMAND" =~ chmod[[:space:]]+(-R[[:space:]]+)?777 ]] && _emit_deny "World-writable permissions"
[[ "$COMMAND" =~ mkfs ]] && _emit_deny "Filesystem format"
[[ "$COMMAND" =~ git[[:space:]]+push[[:space:]]+(-f|--force)[[:space:]]+(origin[[:space:]]+)?(main|master) ]] && _emit_deny "Force push to main/master"
[[ "$COMMAND" =~ git[[:space:]]+reset[[:space:]]+--hard ]] && _emit_deny "git reset --hard"
[[ "$COMMAND" =~ (curl|wget)[[:space:]].*\|[[:space:]]*(sh|bash|zsh|python|perl) ]] && _emit_deny "Piping remote content to shell"
[[ "$COMMAND" =~ eval[[:space:]]+\$\( ]] && _emit_deny "eval with command substitution"
[[ "$COMMAND" =~ (npm|pnpm)[[:space:]]+publish ]] && [[ ! "$COMMAND" =~ --dry-run ]] && _emit_deny "npm publish without --dry-run"

# All checks passed
_emit_allow "Pattern checks passed"
