"""Registry Builder - Converts structured registry data to platform-specific formats.

Currently supports:
- Building Markdown personas for Claude Code (.claude/rules/persona-*.md)
- Injecting user profile context into generated personas
"""

import logging
from pathlib import Path
from typing import List

from c4.supervisor.agent_graph.loader import AgentGraphLoader
from c4.supervisor.agent_graph.models import AgentDefinition

logger = logging.getLogger(__name__)

class RegistryBuilder:
    def __init__(self, project_root: Path):
        self.project_root = project_root
        # Initialize loader with system defaults
        self.loader = AgentGraphLoader()

    def build_for_claude(self) -> List[str]:
        """Build registry artifacts for Claude Code.

        Generates .claude/rules/persona-{id}.md files from agent definitions.
        Injects user profile context if available.

        Returns:
            List of generated file paths (relative to project root).
        """
        generated_files = []
        rules_dir = self.project_root / ".claude" / "rules"
        rules_dir.mkdir(parents=True, exist_ok=True)

        # Load all agents
        try:
            agents = self.loader.load_agents()
        except Exception as e:
            logger.error(f"Failed to load agents: {e}")
            return []

        # Load user profile (optional, graceful degradation)
        profile = self._load_profile()

        for agent_def in agents:
            agent = agent_def.agent
            filename = f"persona-{agent.id}.md"
            file_path = rules_dir / filename

            content = self._format_agent_markdown(agent_def, profile)
            file_path.write_text(content)
            generated_files.append(str(file_path.relative_to(self.project_root)))

        return generated_files

    def _load_profile(self):
        """Load user profile if available. Returns None on failure."""
        try:
            from .profile_loader import ProfileLoader

            c4_dir = self.project_root / ".c4"
            loader = ProfileLoader(c4_dir)
            return loader.load()
        except Exception as e:
            logger.debug(f"Profile not available: {e}")
            return None

    def _format_agent_markdown(self, agent_def: AgentDefinition, profile=None) -> str:
        """Format an AgentDefinition into a Markdown document."""
        a = agent_def.agent
        p = a.persona

        lines = []
        lines.append(f"# Persona: {a.name}")
        lines.append(f"> **Role**: {p.role}")
        lines.append(f"> **Expertise**: {p.expertise}")
        lines.append("")

        # Personality
        if p.personality:
            lines.append("## Personality")
            traits = p.personality
            if traits.style:
                lines.append(f"- **Style**: {traits.style}")
            if traits.communication:
                lines.append(f"- **Communication**: {traits.communication}")
            if traits.approach:
                lines.append(f"- **Approach**: {traits.approach}")
            lines.append("")

        # Skills
        if a.skills:
            lines.append("## Skills")
            if a.skills.primary:
                lines.append(f"- **Primary**: {', '.join(a.skills.primary)}")
            if a.skills.secondary:
                lines.append(f"- **Secondary**: {', '.join(a.skills.secondary)}")
            lines.append("")

        # Instructions
        if a.instructions:
            if a.instructions.on_receive:
                lines.append("## Instructions (On Receive)")
                lines.append(a.instructions.on_receive)
                lines.append("")
            if a.instructions.on_handoff:
                lines.append("## Instructions (On Handoff)")
                lines.append(a.instructions.on_handoff)
                lines.append("")

        # User Context (from profile)
        user_context = self._build_user_context_section(a.id, profile)
        if user_context:
            lines.append(user_context)
            lines.append("")

        # Footer
        lines.append("---")
        lines.append(f"*Generated by C4 Registry Builder from {a.id}*")

        return "\n".join(lines)

    def _build_user_context_section(self, agent_id: str, profile) -> str | None:
        """Build a User Context section from profile for a specific agent."""
        if not profile:
            return None

        lines = ["## User Context"]
        has_content = False

        # Review-related agents
        if "reviewer" in agent_id or "review" in agent_id:
            if profile.review.focus:
                lines.append(f"- **Review Focus**: {', '.join(profile.review.focus)}")
                has_content = True
            if profile.review.paper_criteria:
                lines.append(
                    f"- **Paper Criteria**: {', '.join(profile.review.paper_criteria)}"
                )
                has_content = True
            lines.append(f"- **Strictness**: {profile.review.strictness}")
            has_content = True

        # Writer-related agents
        if "writer" in agent_id:
            lines.append(f"- **Language**: {profile.writing.language}")
            lines.append(f"- **Formality**: {profile.writing.formality}")
            has_content = True

        # Domain expertise for all agents
        if profile.expertise.domains:
            relevant = [f"{d} ({lvl})" for d, lvl in profile.expertise.domains.items()]
            lines.append(f"- **Expertise**: {', '.join(relevant)}")
            has_content = True

        # Research fields
        if profile.expertise.research_fields:
            lines.append(
                f"- **Research Fields**: {', '.join(profile.expertise.research_fields)}"
            )
            has_content = True

        # Per-agent overrides
        if agent_id in profile.persona_overrides:
            lines.append(f"- **Special Instructions**: {profile.persona_overrides[agent_id]}")
            has_content = True

        # Adapted Workflow (when workflow weights exist for this agent)
        if hasattr(profile, 'workflow_weights') and agent_id in profile.workflow_weights:
            agent_weights = profile.workflow_weights[agent_id]
            if agent_weights:
                steps = self._get_workflow_steps(agent_id)
                if steps:
                    from c4.system.registry.profile import WorkflowWeight

                    def _step_order(step: dict) -> int:
                        w = agent_weights.get(step["id"])
                        if isinstance(w, WorkflowWeight) and w.order > 0:
                            return w.order
                        elif isinstance(w, dict) and w.get("order", 0) > 0:
                            return w["order"]
                        return step.get("default_order", 99)

                    sorted_steps = sorted(steps, key=_step_order)
                    lines.append("")
                    lines.append("### Adapted Workflow")
                    for i, step in enumerate(sorted_steps, 1):
                        w = agent_weights.get(step["id"])
                        if isinstance(w, dict):
                            w = WorkflowWeight(**w)
                        elif not isinstance(w, WorkflowWeight):
                            w = WorkflowWeight()
                        emphasis = (
                            "HIGH" if w.weight > 0.7
                            else "MEDIUM" if w.weight > 0.4
                            else "LOW"
                        )
                        desc = step["description"]
                        if w.custom_substeps:
                            desc += f" (+ {', '.join(w.custom_substeps)})"
                        lines.append(f"- Step {i} [{emphasis}]: {desc}")
                    has_content = True

        return "\n".join(lines) if has_content else None

    def _get_workflow_steps(self, agent_id: str) -> list[dict] | None:
        """Get workflow_steps for a specific agent."""
        try:
            agents = self.loader.load_agents()
            for agent_def in agents:
                if agent_def.agent.id == agent_id:
                    steps = (
                        agent_def.agent.instructions
                        and agent_def.agent.instructions.workflow_steps
                    )
                    if steps:
                        return [
                            {
                                "id": s.id,
                                "description": s.description,
                                "default_order": s.default_order,
                            }
                            for s in steps
                        ]
        except Exception:
            pass
        return None
