"""Registry Builder - Converts structured registry data to platform-specific formats.

Currently supports:
- Building Markdown personas for Claude Code (.claude/rules/persona-*.md)
"""

from pathlib import Path
import logging
from typing import List

from c4.supervisor.agent_graph.loader import AgentGraphLoader
from c4.supervisor.agent_graph.models import AgentDefinition

logger = logging.getLogger(__name__)

class RegistryBuilder:
    def __init__(self, project_root: Path):
        self.project_root = project_root
        # Initialize loader with system defaults
        self.loader = AgentGraphLoader()
        
    def build_for_claude(self) -> List[str]:
        """Build registry artifacts for Claude Code.
        
        Generates .claude/rules/persona-{id}.md files from agent definitions.
        
        Returns:
            List of generated file paths (relative to project root).
        """
        generated_files = []
        rules_dir = self.project_root / ".claude" / "rules"
        rules_dir.mkdir(parents=True, exist_ok=True)
        
        # Load all agents
        try:
            agents = self.loader.load_agents()
        except Exception as e:
            logger.error(f"Failed to load agents: {e}")
            return []

        for agent_def in agents:
            agent = agent_def.agent
            filename = f"persona-{agent.id}.md"
            file_path = rules_dir / filename
            
            content = self._format_agent_markdown(agent_def)
            file_path.write_text(content)
            generated_files.append(str(file_path.relative_to(self.project_root)))
            
        return generated_files

    def _format_agent_markdown(self, agent_def: AgentDefinition) -> str:
        """Format an AgentDefinition into a Markdown document."""
        a = agent_def.agent
        p = a.persona
        
        lines = []
        lines.append(f"# Persona: {a.name}")
        lines.append(f"> **Role**: {p.role}")
        lines.append(f"> **Expertise**: {p.expertise}")
        lines.append("")
        
        # Personality
        if p.personality:
            lines.append("## Personality")
            traits = p.personality
            if traits.style: lines.append(f"- **Style**: {traits.style}")
            if traits.communication: lines.append(f"- **Communication**: {traits.communication}")
            if traits.approach: lines.append(f"- **Approach**: {traits.approach}")
            lines.append("")

        # Skills
        if a.skills:
            lines.append("## Skills")
            if a.skills.primary:
                lines.append(f"- **Primary**: {', '.join(a.skills.primary)}")
            if a.skills.secondary:
                lines.append(f"- **Secondary**: {', '.join(a.skills.secondary)}")
            lines.append("")

        # Instructions
        if a.instructions:
            if a.instructions.on_receive:
                lines.append("## Instructions (On Receive)")
                lines.append(a.instructions.on_receive)
                lines.append("")
            if a.instructions.on_handoff:
                lines.append("## Instructions (On Handoff)")
                lines.append(a.instructions.on_handoff)
                lines.append("")
                
        # Footer
        lines.append("---")
        lines.append(f"*Generated by C4 Registry Builder from {a.id}*")
        
        return "\n".join(lines)
