"""PRManager for C4 worktree-based PR workflow.

Creates and updates GitHub/GitLab PRs for completed task branches.
"""

import logging
import shutil
import subprocess
from dataclasses import dataclass
from pathlib import Path
from typing import Any

logger = logging.getLogger(__name__)


@dataclass
class PRResult:
    """Result of a PR operation."""

    success: bool
    message: str
    pr_url: str | None = None
    pr_number: int | None = None


class PRManager:
    """Manages Pull Request creation and updates for C4 worktrees.

    Uses gh CLI for GitHub operations. Falls back gracefully
    if gh is not installed.
    """

    def __init__(self, project_root: Path):
        """Initialize PRManager.

        Args:
            project_root: Root directory of the project (contains .git/)
        """
        self.root = project_root
        self._gh_available: bool | None = None

    def is_gh_available(self) -> bool:
        """Check if gh CLI is installed and available."""
        if self._gh_available is None:
            self._gh_available = shutil.which("gh") is not None
        return self._gh_available

    def _run_gh(self, *args: str, cwd: Path | None = None) -> subprocess.CompletedProcess:
        """Run a gh CLI command.

        Args:
            *args: Command arguments (e.g., "pr", "create")
            cwd: Working directory for the command

        Returns:
            CompletedProcess with stdout, stderr, and returncode
        """
        cmd = ["gh", *args]
        return subprocess.run(
            cmd,
            cwd=cwd or self.root,
            capture_output=True,
            text=True,
        )

    def get_completed_tasks_summary(
        self,
        tasks: list[dict[str, Any]],
        include_dod: bool = False,
    ) -> str:
        """Format completed tasks into a PR body summary.

        Args:
            tasks: List of task dicts with at least 'task_id' and 'title' keys
            include_dod: Whether to include DoD in the summary

        Returns:
            Formatted markdown string suitable for PR body
        """
        if not tasks:
            return "No tasks completed in this PR."

        lines = ["## Completed Tasks\n"]

        for task in tasks:
            task_id = task.get("task_id", "Unknown")
            title = task.get("title", "Untitled")
            lines.append(f"- **{task_id}**: {title}")

            if include_dod:
                dod = task.get("dod", "")
                if dod:
                    # Indent DoD under the task
                    dod_lines = dod.strip().split("\n")
                    for dod_line in dod_lines[:5]:  # Limit to first 5 lines
                        lines.append(f"  - {dod_line}")
                    if len(dod_lines) > 5:
                        lines.append(f"  - ... ({len(dod_lines) - 5} more)")

        lines.append("")
        lines.append("---")
        lines.append("*Generated by C4 Orchestration System*")

        return "\n".join(lines)

    def get_existing_pr(self, branch: str) -> dict[str, Any] | None:
        """Get existing PR for a branch.

        Args:
            branch: Branch name to check

        Returns:
            Dict with PR info if exists, None otherwise
        """
        if not self.is_gh_available():
            return None

        result = self._run_gh(
            "pr", "view", branch,
            "--json", "number,url,state,title",
        )

        if result.returncode != 0:
            return None

        import json
        try:
            return json.loads(result.stdout)
        except json.JSONDecodeError:
            return None

    def create_or_update_pr(
        self,
        branch: str,
        title: str,
        body: str,
        base_branch: str = "main",
        draft: bool = False,
    ) -> PRResult:
        """Create a new PR or update an existing one.

        Args:
            branch: Source branch for the PR
            title: PR title
            body: PR body/description
            base_branch: Target branch (default: main)
            draft: Whether to create as draft PR

        Returns:
            PRResult with success status and PR info
        """
        if not self.is_gh_available():
            return PRResult(
                success=False,
                message="gh CLI is not installed. Please install it from https://cli.github.com/",
            )

        # Check if PR already exists for this branch
        existing_pr = self.get_existing_pr(branch)

        if existing_pr:
            # Update existing PR
            pr_number = existing_pr.get("number")
            result = self._run_gh(
                "pr", "edit", str(pr_number),
                "--title", title,
                "--body", body,
            )

            if result.returncode != 0:
                return PRResult(
                    success=False,
                    message=f"Failed to update PR #{pr_number}: {result.stderr}",
                    pr_number=pr_number,
                    pr_url=existing_pr.get("url"),
                )

            return PRResult(
                success=True,
                message=f"Updated PR #{pr_number}",
                pr_number=pr_number,
                pr_url=existing_pr.get("url"),
            )

        # Create new PR
        args = [
            "pr", "create",
            "--title", title,
            "--body", body,
            "--base", base_branch,
            "--head", branch,
        ]

        if draft:
            args.append("--draft")

        result = self._run_gh(*args)

        if result.returncode != 0:
            return PRResult(
                success=False,
                message=f"Failed to create PR: {result.stderr}",
            )

        # Extract PR URL from output
        pr_url = result.stdout.strip()

        # Try to get PR number
        pr_number = None
        if pr_url:
            try:
                # URL format: https://github.com/owner/repo/pull/123
                pr_number = int(pr_url.rstrip("/").split("/")[-1])
            except (ValueError, IndexError):
                pass

        return PRResult(
            success=True,
            message=f"Created PR: {pr_url}",
            pr_url=pr_url,
            pr_number=pr_number,
        )

    def merge_and_cleanup(
        self,
        branch: str,
        delete_branch: bool = True,
        squash: bool = False,
    ) -> PRResult:
        """Merge a PR and optionally delete the branch.

        Args:
            branch: Branch with the PR to merge
            delete_branch: Whether to delete the branch after merge
            squash: Whether to squash merge

        Returns:
            PRResult with merge status
        """
        if not self.is_gh_available():
            return PRResult(
                success=False,
                message="gh CLI is not installed",
            )

        existing_pr = self.get_existing_pr(branch)
        if not existing_pr:
            return PRResult(
                success=False,
                message=f"No PR found for branch: {branch}",
            )

        pr_number = existing_pr.get("number")
        args = ["pr", "merge", str(pr_number), "--auto"]

        if squash:
            args.append("--squash")
        else:
            args.append("--merge")

        if delete_branch:
            args.append("--delete-branch")

        result = self._run_gh(*args)

        if result.returncode != 0:
            return PRResult(
                success=False,
                message=f"Failed to merge PR #{pr_number}: {result.stderr}",
                pr_number=pr_number,
                pr_url=existing_pr.get("url"),
            )

        return PRResult(
            success=True,
            message=f"Merged PR #{pr_number}",
            pr_number=pr_number,
            pr_url=existing_pr.get("url"),
        )
